let alumnograduacion_def_tests =[
    ['alumnograduacion', 'alumnograduacion_login', 'input', 1, 'Comprobar tamaño mínimo login', 'ADD', 'alumnograduacion_login_min_size_KO', 'El login es inferior al tamaño mínimo. Debe estar entre 4 y 15 caracteres'],
    /*['alumnograduacion', 'alumnograduacion_login', 'input', 2, 'Comprobar tamaño máximo login', 'ADD', 'alumnograduacion_login_max_size_KO', 'El login excede el tamaño máximo. Debe estar entre 4 y 15 caracteres'],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 3, 'Comprobar tamaño formato login', 'ADD', 'alumnograduacion_login_format_KO', 'El login no cumple el formato. Debe estar entre 4 y 15 caracteres alfabéticos sin acentos ni ñ'],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 4, 'Comprobar campo válido login', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 5, 'Comprobar tamaño mínimo login', 'EDIT', 'alumnograduacion_login_min_size_KO', 'El login es inferior al tamaño mínimo. Debe estar entre 4 y 15 caracteres'],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 6, 'Comprobar tamaño máximo login', 'EDIT', 'alumnograduacion_login_max_size_KO', 'El login excede el tamaño máximo. Debe estar entre 4 y 15 caracteres'],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 7, 'Comprobar tamaño formato login', 'EDIT', 'alumnograduacion_login_format_KO', 'El login no cumple el formato. Debe estar entre 4 y 15 caracteres alfabéticos sin acentos ni ñ']
    ['alumnograduacion', 'alumnograduacion_login', 'input', 8, 'Comprobar campo válido login', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 9, 'Comprobar tamaño máximo login', 'SEARCH', 'alumnograduacion_login_max_size_KO', 'El login excede el tamaño máximo. Debe estar entre 4 y 15 caracteres'],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 10, 'Comprobar tamaño formato login', 'SEARCH', 'alumnograduacion_login_format_KO', 'El login no cumple el formato. Debe estar entre 4 y 15 caracteres alfabéticos sin acentos ni ñ'],
    ['alumnograduacion', 'alumnograduacion_login', 'input', 11, 'Comprobar campo válido login', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 12, 'Comprobar tamaño mínimo password', 'ADD', 'alumnograduacion_password_min_size_KO', 'La password es inferior al tamaño mínimo. Debe estar entre 8 y 64 caracteres'],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 13, 'Comprobar tamaño máximo password', 'ADD', 'alumnograduacion_password_max_size_KO', 'La password excede al tamaño máximo. Debe estar entre 8 y 64 caracteres'],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 14, 'Comprobar formato password', 'ADD', 'alumnograduacion_password_format_KO', 'La password no cumple el formato. Debe estar entre 8 y 64 caracteres alfabéticos y espacios, sin acentos ni ñ']
    ['alumnograduacion', 'alumnograduacion_password', 'input', 15, 'Comprobar campo válido password', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 16, 'Comprobar tamaño mínimo password', 'EDIT', 'alumnograduacion_password_min_size_KO', 'La password es inferior al tamaño mínimo. Debe estar entre 8 y 64 caracteres'],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 17, 'Comprobar tamaño máximo password', 'EDIT', 'alumnograduacion_password_max_size_KO', 'La password excede al tamaño máximo. Debe estar entre 8 y 64 caracteres'],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 18, 'Comprobar formato password', 'EDIT', 'alumnograduacion_password_format_KO', 'La password no cumple el formato. Debe estar entre 8 y 64 caracteres alfabéticos y espacios, sin acentos ni ñ'],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 19, 'Comprobar campo válido password', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 20, 'Comprobar tamaño máximo password', 'SEARCH', 'alumnograduacion_password_max_size_KO', 'La password excede al tamaño máximo. Debe tener vomo máximo 64 caracteres'],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 21, 'Comprobar formato password', 'SEARCH', 'alumnograduacion_password_format_KO', 'La password no cumple el formato. Debe tener alfabéticos y espacios, sin acentos ni ñ'],
    ['alumnograduacion', 'alumnograduacion_password', 'input', 22, 'Comprobar campo válido password', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 23, 'Comprobar tamaño mínimo nombre', 'ADD', 'alumnograduacion_nombre_min_size_KO', 'El nombre es inferior al tamaño mínimo. Debe estar entre 2 y 25 caracteres']
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 24, 'Comprobar tamaño máximo nombre', 'ADD', 'alumnograduacion_nombre_max_size-KO', 'El nombre excede el tamaño máximo. Debe estar entre 2 y 25 caracteres'],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 25, 'Comprobar formato nombre', 'ADD', 'alumnograduacion_nombre_format_KO', 'El nombre no cumple el formato. Debe estar entre 2 y 25 caracteres alfabéticos con espacios, acentos y ñ'],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 26, 'Comprobar campo válido nombre', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 27, 'Comprobar tamaño mínimo nombre', 'EDIT', 'alumnograduacion_nombre_min_size_KO', 'El nombre es inferior al tamaño mínimo. Debe estar entre 2 y 25 caracteres'],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 28, 'Comprobar tamaño máximo nombre', 'EDIT', 'alumnograduacion_nombre_max_size-KO', 'El nombre excede el tamaño máximo. Debe estar entre 2 y 25 caracteres'],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 29, 'Comprobar formato nombre', 'EDIT', 'alumnograduacion_nombre_format_KO', 'El nombre no cumple el formato. Debe estar entre 2 y 25 caracteres alfabéticos con espacios, acentos y ñ'],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 30, 'Comprobar campo válido nombre', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 31, 'Comprobar tamaño máximo nombre', 'SEARCH', 'alumnograduacion_nombre_max_size-KO', 'El nombre excede el tamaño máximo. Debe tener como máximo 25 caracteres'],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 32, 'Comprobar formato nombre', 'SEARCH', 'alumnograduacion_nombre_format_KO', 'El nombre no cumple el formato. Solo puede contener alfabéticos y espacios, sin acentos ni ñ'],
    ['alumnograduacion', 'alumnograduacion_nombre', 'input', 33, 'Comprobar campo válido nombre', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 34, 'Comprobar tamaño mínimo apellidos', 'ADD', 'alumnograduacion_apellidos_min_size_KO', 'Los apellidos son inferiores al tamaño mínimo. Deben estar entre 2 y 35 caracteres'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 35, 'Comprobar tamaño máximo apellidos', 'ADD', 'alumnograduacion_apellidos_max_size_KO', 'Los apellidos exceden el tamaño máximo. Deben estar entre 2 y 35 caracteres'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 36, 'Comprobar formato apellidos', 'ADD', 'alumnograduacion_apellidos_format_KO', 'Los apellidos no cumplen el formato. Deben estar entre 2 y 35 caracteres alfabéticos con espacios, acentos y ñ'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 37, 'Comprobar campo válido apellidos', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 38, 'Comprobar tamaño mínimo apellidos', 'EDIT', 'alumnograduacion_apellidos_min_size_KO', 'Los apellidos son inferiores al tamaño mínimo. Deben estar entre 2 y 35 caracteres'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 39, 'Comprobar tamaño máximo apellidos', 'EDIT', 'alumnograduacion_apellidos_max_size_KO', 'Los apellidos exceden el tamaño máximo. Deben estar entre 2 y 35 caracteres'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 40, 'Comprobar formato apellidos', 'EDIT', 'alumnograduacion_apellidos_format_KO', 'Los apellidos no cumplen el formato. Deben estar entre 2 y 35 caracteres alfabéticos con espacios, acentos y ñ'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 41, 'Comprobar campo válido apellidos', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 42, 'Comprobar tamaño máximo apellidos', 'SEARCH', 'alumnograduacion_apellidos_max_size_KO', 'Los apellidos exceden el tamaño máximo. Deben tener como máximo 35 caracteres'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 43, 'Comprobar formato apellidos', 'SEARCH', 'alumnograduacion_apellidos_format_KO', 'Los apellidos no cumplen el formato. Solo pueden contener alfabéticos y espacios, sin acentos ni ñ'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 'input', 44, 'Comprobar campo válido apellidos', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 45, 'Comprobar tamaño mínimo titulación', 'ADD', 'alumnograduacion_titulacion_min_size_KO', 'La titulación es inferior al tamaño mínimo. Debe estar entre 3 y 4 caracteres'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 46, 'Comprobar tamaño máximo titulación', 'ADD', 'alumnograduacion_titulacion_max_size_KO', 'La titulación excede el tamaño máximo. Debe estar entre 3 y 4 caracteres'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 47, 'Comprobar formato titulación', 'ADD', 'alumnograduacion_titulacion_format_KO', 'La titulación no cumple el formato. Debe ser una de las siguientes: GREI, GRIA, MEI, MIA, PCEO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 48, 'Comprobar campo válido titulación', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 49, 'Comprobar tamaño mínimo titulación', 'EDIT', 'alumnograduacion_titulacion_min_size_KO', 'La titulación es inferior al tamaño mínimo. Debe estar entre 3 y 4 caracteres'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 50, 'Comprobar tamaño máximo titulación', 'EDIT', 'alumnograduacion_titulacion_max_size_KO', 'La titulación excede el tamaño máximo. Debe estar entre 3 y 4 caracteres'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 51, 'Comprobar formato titulación', 'EDIT', 'alumnograduacion_titulacion_format_KO', 'La titulación no cumple el formato. Debe ser una de las siguientes: GREI, GRIA, MEI, MIA, PCEO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 52, 'Comprobar campo válido titulación', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 53, 'Comprobar tamaño máximo titulación', 'SEARCH', 'alumnograduacion_titulacion_max_size_KO', 'La titulación excede el tamaño máximo. Debe tener como máximo 4 caracteres'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 54, 'Comprobar formato titulación', 'SEARCH', 'alumnograduacion_titulacion_format_KO', 'La cadena introducida no coincide con ninguna de las opciones posibles: GREI, GRIA, MEI, MIA, PCEO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 'select', 55, 'Comprobar campo válido titulación', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 56, 'Comprobar tamaño mínimo DNI', 'ADD', 'alumnograduacion_dni_min_size_KO', 'El DNI es inferior al tamaño mínimo. Debe tener 8 dígitos y una letra mayúscula'],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 57, 'Comprobar tamaño máximo DNI', 'ADD', 'alumnograduacion_dni_max_size_KO', 'El DNI excede el tamaño máximo. Debe tener 8 dígitos y una letra mayúscula'],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 58, 'Comprobar formato DNI', 'ADD', 'alumnograduacion_dni_format_KO', 'El DNI no cumple el formato. Debe tener 8 dígitos y una letra mayúscula']
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 59, 'Comprobar campo válido DNI', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 60, 'Comprobar tamaño mínimo DNI', 'EDIT', 'alumnograduacion_dni_min_size_KO', 'El DNI es inferior al tamaño mínimo. Debe tener 8 dígitos y una letra mayúscula'],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 61, 'Comprobar tamaño máximo DNI', 'EDIT', 'alumnograduacion_dni_max_size_KO', 'El DNI excede el tamaño máximo. Debe tener 8 dígitos y una letra mayúscula'],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 62, 'Comprobar formato DNI', 'EDIT', 'alumnograduacion_dni_format_KO', 'El DNI no cumple el formato. Debe tener 8 dígitos y una letra mayúscula'],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 63, 'Comprobar campo válido DNI', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 64, 'Comprobar tamaño máximo DNI', 'SEARCH', 'alumnograduacion_dni_max_size_KO', 'El DNI excede el tamaño máximo. Debe tener 8 dígitos y una letra mayúscula'],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 65, 'Comprobar formato DNI', 'SEARCH', 'alumnograduacion_dni_format_KO', 'El DNI no cumple el formato. Debe tener 8 dígitos y una letra mayúscula'],
    ['alumnograduacion', 'alumnograduacion_dni', 'input', 66, 'Comprobar campo válido DNI', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 67, 'Comprobar tamaño mínimo teléfono', 'ADD', 'alumnograduacion_telefono_min_size_KO', 'El teléfono es inferior al tamaño mínimo. Debe tener 9 dígitos']
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 68, 'Comprobar tamaño máximo teléfono', 'ADD', 'alumnograduacion_telefono_max_size_KO', 'El teléfono excede el tamaño máximo. Debe tener 9 dígitos'],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 69, 'Comprobar formato teléfono', 'ADD', 'alumnograduacion_telefono_format_KO', 'El teléfono no cumple el formato. Debe tener 9 dígitos del 0 al 9'],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 70, 'Comprobar campo válido teléfono', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 71, 'Comprobar tamaño mínimo teléfono', 'EDIT', 'alumnograduacion_telefono_min_size_KO', 'El teléfono es inferior al tamaño mínimo. Debe tener 9 dígitos'],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 72, 'Comprobar tamaño máximo teléfono', 'EDIT', 'alumnograduacion_telefono_max_size_KO', 'El teléfono excede el tamaño máximo. Debe tener 9 dígitos'],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 73, 'Comprobar formato teléfono', 'EDIT', 'alumnograduacion_telefono_format_KO', 'El teléfono no cumple el formato. Debe tener 9 dígitos del 0 al 9'],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 74, 'Comprobar campo válido teléfono', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 75, 'Comprobar tamaño máximo teléfono', 'SEARCH', 'alumnograduacion_telefono_max_size_KO', 'El teléfono excede el tamaño máximo. Debe tener 9 dígitos'],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 76, 'Comprobar formato teléfono', 'SEARCH', 'alumnograduacion_telefono_format_KO', 'El teléfono no cumple el formato. Debe tener 9 dígitos del 0 al 9'],
    ['alumnograduacion', 'alumnograduacion_telefono', 'input', 77, 'Comprobar campo válido teléfono', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 78, 'Comprobar tamaño mínimo dirección', 'ADD', 'alumnograduacion_direccion_min_size_KO', 'La dirección es inferior al mínimo número de caracteres permitidos. No puede ser null'],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 79, 'Comprobar tamaño máximo dirección', 'ADD', 'alumnograduacion_direccion_max_size_KO', 'La dirección excede el máximo número de caracteres permitidos. Debe ser inferior a 100 caracteres']
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 80, 'comprobar formato direccion', 'ADD', 'alumnograduacion_direccion_format_KO', 'La dirección no cumple el formato. Solo puede contener alfanuméricos con acentos, ñ y espacios'],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 81, 'Comprobar campo válido dirección', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 82, 'Comprobar tamaño mínimo dirección', 'EDIT', 'alumnograduacion_direccion_min_size_KO', 'La dirección es inferior al mínimo número de caracteres permitidos. No puede ser null'],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 83, 'Comprobar tamaño máximo dirección', 'EDIT', 'alumnograduacion_direccion_max_size_KO', 'La dirección excede el máximo número de caracteres permitidos. Debe ser inferior a 100 caracteres'],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 84, 'comprobar formato direccion', 'EDIT', 'alumnograduacion_direccion_format_KO', 'La dirección no cumple el formato. Solo puede contener alfanuméricos con acentos, ñ y espacios'],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 85, 'Comprobar campo válido dirección', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 86, 'Comprobar tamaño máximo dirección', 'SEARCH', 'alumnograduacion_direccion_max_size_KO', 'La dirección excede el máximo número de caracteres permitidos. Debe ser inferior a 100 caracteres'],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 87, 'comprobar formato direccion', 'SEARCH', 'alumnograduacion_direccion_format_KO', 'La dirección no coincide con ninguna porque no cumple el formato. Solo puede contener alfanuméricos con acentos, ñ y espacios'],
    ['alumnograduacion', 'alumnograduacion_direccion', 'input', 88, 'Comprobar campo válido dirección', 'SEARCH', true, ''],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 89, 'Comprobar tamaño mínimo email', 'ADD', 'alumnograduacion_email_min_size_KO', 'El email es inferior al tamaño mínimo. No puede ser null'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 90, 'Comprobar tamaño máximo email', 'ADD', 'alumnograduacion_email_max_size_KO', 'El email excede el tamaño máximo. No puede superar los 40 caracteres'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 91, 'Comprobar formato email', 'ADD', 'alumnograduacion_email_format_KO', 'El email no cumple el formato. Debe ser un email válido'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 91, 'Comprobar campo válido email', 'ADD', true, ''],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 93, 'Comprobar tamaño mínimo email', 'EDIT', 'alumnograduacion_email_min_size_KO', 'El email es inferior al tamaño mínimo. No puede ser null'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 94, 'Comprobar tamaño máximo email', 'EDIT', 'alumnograduacion_email_max_size_KO', 'El email excede el tamaño máximo. No puede superar loa 40 caracteres'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 95, 'Comprobar formato email', 'EDIT', 'alumnograduacion_email_format_KO', 'El email no cumple el formato. Debe ser un email válido'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 96, 'Comprobar campo válido email', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 97, 'Comprobar tamaño máximo email', 'SEARCH', 'alumnograduacion_email_max_size_KO', 'El email excede el tamaño máximo. Debe tener emenos de 40 caracteres'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 98, 'Comprobar formato email', 'SEARCH', 'alumnograduacion_email_format_KO', 'El email no cumple el formato. Debe ser un email válido'],
    ['alumnograduacion', 'alumnograduacion_email', 'input', 99, 'Comprobar campo válido email', 'SEARCH', true, ''],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 100, 'Comprobar existencia del archivo', 'ADD', 'nuevo_alumnograduacion_fotoacto_not_exists_file_KO', 'El fichero no existe. Debe subir una foto'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 101, 'Comprobar formato del nombre del archivo', 'ADD', 'nuevo_alumnograduacion_fotoacto_name_format_KO', 'El nombre del fichero no es correcto. Solo se permiten entre 7 y 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."']
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 102, 'Comprobar formato del archivo', 'ADD', 'nuevo_alumnograduacion_fotoacto_type_file_KO', 'El formato del fichero no es correcto. Solo se permiten los formatos: jpg'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 103, 'Comprobar tamaño del archivo', 'ADD', 'nuevo_alumnograduacion_fotoacto_max_size_file_KO', 'El tamaño del fichero no es correcto. El tamaño máximo permitido es 2MB'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 104, 'Comprobar tamaño mínimo del nombre del archivo', 'ADD', 'nuevo_alumnograduacion_fotoacto_name_min_size_KO', 'El nombre del fichero es inferior al tamaño mínimo. Debe tener entre 7 y 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 105, 'Comprobar tamaño máximo del nombre del archivo', 'ADD', 'nuevo_alumnograduacion_fotoacto_name_max_size_KO', 'El nombre del fichero excede el tamaño máximo. Debe tener entre 7 y 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 106, 'Comprobar fichero válido', 'ADD', true, ''],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 107, 'Comprobar existencia del archivo', 'EDIT', 'nuevo_alumnograduacion_fotoacto_not_exists_file_KO', 'El fichero no existe. Debe subir una foto'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 108, 'Comprobar formato del nombre del archivo', 'EDIT', 'nuevo_alumnograduacion_fotoacto_name_format_KO', 'El nombre del fichero no es correcto. Solo se permiten entre 7 y 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 109, 'Comprobar formato del archivo', 'EDIT', 'nuevo_alumnograduacion_fotoacto_type_file_KO', 'El formato del fichero no es correcto. Solo se permiten los formatos: jpg'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 110, 'Comprobar tamaño del archivo', 'EDIT', 'nuevo_alumnograduacion_fotoacto_max_size_file_KO', 'El tamaño del fichero no es correcto. El tamaño máximo permitido es 2MB'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 111, 'Comprobar tamaño mínimo del nombre del archivo', 'EDIT', 'nuevo_alumnograduacion_fotoacto_name_min_size_KO', 'El nombre del fichero es inferior al tamaño mínimo. Debe tener entre 7 y 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 112, 'Comprobar tamaño máximo del nombre del archivo', 'EDIT', 'nuevo_alumnograduacion_fotoacto_name_max_size_KO', 'El nombre del fichero excede el tamaño máximo. Debe tener entre 7 y 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 'inputfile', 113, 'Comprobar fichero válido', 'EDIT', true, ''],
    ['alumnograduacion', 'alumnograduacion_fotoacto', 'input', 114, 'Comprobar tamaño máximo de nombre de búsqueda', 'SEARCH', 'alumnograduacion_fotoacto_name_max_size_KO', 'El nombre del fichero excede el tamaño máximo. Debe tener menos de 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."'],
    ['alumnograduacion', 'alumnograduacion_fotoacto', 'input', 115, 'Comprobar formato de búsqueda', 'SEARCH', 'alumnograduacion_fotoacto_name_format_KO', 'El nombre del fichero no es correcto. Solo se permiten máximo 40 caracteres alfabéticos (sin acentos, ñ, ni espacios) y "."'], 
    ['alumnograduacion', 'alumnograduacion_fotoacto', 'input', 116, 'Comprobar búsqueda válida', 'SEARCH', true, ''], */
    

]



let alumnograduacion_tests_fields =[
    ['alumnograduacion', 'alumnograduacion_login', 1, 1, 'ADD', [{alumnograduacion_login: 'a'}], 'alumnograduacion_login_min_size_KO'],
    /*['alumnograduacion', 'alumnograduacion_login', 1, 2, 'ADD', [{alumnograduacion_login: 'ada'}], 'alumnograduacion_login_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 2, 3, 'ADD', [{alumnograduacion_login: 'a.repeat(15)'}], 'alumnograduacion_login_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 3, 4, 'ADD', [{alumnograduacion_login: 'martiño'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 3, 5, 'ADD', [{alumnograduacion_login: '#alicia'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 3, 6, 'ADD', [{alumnograduacion_login: 'maría'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 3, 7, 'ADD', [{alumnograduacion_login: 'sebas22'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 4, 8, 'ADD', [{alumnograduacion_login: 'javi'}], true],
    ['alumnograduacion', 'alumnograduacion_login', 5, 9, 'EDIT', [{alumnograduacion_login: 'a'}], 'alumnograduacion_login_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 5, 10, 'EDIT', [{alumnograduacion_login: 'ada'}], 'alumnograduacion_login_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 6, 11, 'EDIT', [{alumnograduacion_login: 'a.repeat(15)'}], 'alumnograduacion_login_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 7, 12, 'EDIT', [{alumnograduacion_login: 'martiño'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 7, 13, 'EDIT', [{alumnograduacion_login: '#alicia'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 7, 14, 'EDIT', [{alumnograduacion_login: 'maría'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 7, 15, 'EDIT', [{alumnograduacion_login: 'sebas22'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 8, 16, 'EDIT', [{alumnograduacion_login: 'javi'}], true],
    ['alumnograduacion', 'alumnograduacion_login', 9, 17, 'SEARCH', [{alumnograduacion_login: 'a.repeat(15)'}], 'alumnograduacion_login_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 10, 18, 'SEARCH', [{alumnograduacion_login: 'martiño'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 10, 19, 'SEARCH', [{alumnograduacion_login: '#alicia'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 10, 20, 'SEARCH', [{alumnograduacion_login: 'maría'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 10, 21, 'SEARCH', [{alumnograduacion_login: 'sebas22'}], 'alumnograduacion_login_format_KO'],
    ['alumnograduacion', 'alumnograduacion_login', 11, 22, 'SEARCH', [{alumnograduacion_login: 'javi'}], true],
    ['alumnograduacion', 'alumnograduacion_password', 12, 23, 'ADD', [{alumnograduacion_password: 'f'}], 'alumnograduacion_password_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 12, 24, 'ADD', [{alumnograduacion_password: 'fffffff'}], 'alumnograduacion_password_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 13, 25, 'ADD', [{alumnograduacion_password: 'f.repeat(100)'}], 'alumnograduacion_password_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 14, 26, 'ADD', [{alumnograduacion_password: '34fifi98t'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 14, 27, 'ADD', [{alumnograduacion_password: '#midsomar'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 14, 28, 'ADD', [{alumnograduacion_password: 'San Martiño'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 14, 29, 'ADD', [{alumnograduacion_password: 'lucíaDerecho'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 15, 30, 'ADD', [{alumnograduacion_password: 'rlcfabiadice'}], true],
    ['alumnograduacion', 'alumnograduacion_password', 16, 31, 'EDIT', [{alumnograduacion_password: 'f'}], 'alumnograduacion_password_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 16, 32, 'EDIT', [{alumnograduacion_password: 'fffffff'}], 'alumnograduacion_password_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 17, 33, 'EDIT', [{alumnograduacion_password: 'f'.repeat(101)}], 'alumnograduacion_password_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 18, 34, 'EDIT', [{alumnograduacion_password: '34fifi98t'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 18, 35, 'EDIT', [{alumnograduacion_password: '#midsomar'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 18, 36, 'EDIT', [{alumnograduacion_password: 'San Martiño'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 18, 37, 'EDIT', [{alumnograduacion_password: 'lucíaDerecho'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 19, 38, 'EDIT', [{alumnograduacion_password: 'rlcfabiadice'}], true],
    ['alumnograduacion', 'alumnograduacion_password', 20, 39, 'SEARCH', [{alumnograduacion_password: 'f'.repeat(101)}], 'alumnograduacion_password_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 21, 40, 'SEARCH', [{alumnograduacion_password: '34fifi98t'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 21, 41, 'SEARCH', [{alumnograduacion_password: '#midsomar'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 21, 42, 'SEARCH', [{alumnograduacion_password: 'San Martiño'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 21, 43, 'SEARCH', [{alumnograduacion_password: 'lucíaDerecho'}], 'alumnograduacion_password_format_KO'],
    ['alumnograduacion', 'alumnograduacion_password', 22, 44, 'SEARCH', [{alumnograduacion_password: 'rlcfabiadice'}], true],
    ['alumnograduacion', 'alumnograduacion_nombre', 23, 45, 'ADD', [{alumnograduacion_nombre: 'a'}], 'alumnograduacion_nombre_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 23, 46, 'ADD', [{alumnograduacion_nombre: 'a'}], 'alumnograduacion_nombre_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 24, 47, 'ADD', [{alumnograduacion_nombre: 'a.repeat(26)'}], 'alumnograduacion_nombre_max_size-KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 25, 48, 'ADD', [{alumnograduacion_nombre: '#alicia'}], 'alumnograduacion_nombre_format_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 25, 49, 'ADD', [{alumnograduacion_nombre: 'sebas22'}], 'alumnograduacion_nombre_format_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 26, 50, 'ADD', [{alumnograduacion_nombre: 'Ana María'}], true],
    ['alumnograduacion', 'alumnograduacion_nombre', 27, 51, 'EDIT', [{alumnograduacion_nombre: 'a'}], 'alumnograduacion_nombre_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 27, 52, 'EDIT', [{alumnograduacion_nombre: 'a'}], 'alumnograduacion_nombre_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 28, 53, 'EDIT', [{alumnograduacion_nombre: 'a.repeat(26)'}], 'alumnograduacion_nombre_max_size-KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 29, 54, 'EDIT', [{alumnograduacion_nombre: '#alicia'}], 'alumnograduacion_nombre_format_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 29, 55, 'EDIT', [{alumnograduacion_nombre: 'sebas22'}], 'alumnograduacion_nombre_format_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 30, 56, 'EDIT', [{alumnograduacion_nombre: 'Ana María'}], true],
    ['alumnograduacion', 'alumnograduacion_nombre', 31, 57, 'SEARCH', [{alumnograduacion_nombre: 'a.repeat(26)'}], 'alumnograduacion_nombre_max_size-KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 32, 58, 'SEARCH', [{alumnograduacion_nombre: '#alicia'}], 'alumnograduacion_nombre_format_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 32, 59, 'SEARCH', [{alumnograduacion_nombre: 'sebas22'}], 'alumnograduacion_nombre_format_KO'],
    ['alumnograduacion', 'alumnograduacion_nombre', 33, 60, 'SEARCH', [{alumnograduacion_nombre: 'Ana María'}], true],
    ['alumnograduacion', 'alumnograduacion_apellidos', 34, 61, 'ADD', [{alumnograduacion_apellidos: ''}], 'alumnograduacion_apellidos_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 34, 62, 'ADD', [{alumnograduacion_apellidos: 'a'}], 'alumnograduacion_apellidos_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 35, 63, 'ADD', [{alumnograduacion_apellidos: 'a.repeat(36)'}], 'alumnograduacion_apellidos_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 36, 64, 'ADD', [{alumnograduacion_apellidos: '#alicia'}], 'alumnograduacion_apellidos_format_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 36, 65, 'ADD', [{alumnograduacion_apellidos: 'sebas22'}], 'alumnograduacion_apellidos_format_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 37, 66, 'ADD', [{alumnograduacion_apellidos: 'Fernández Rodríguez'}], true],
    ['alumnograduacion', 'alumnograduacion_apellidos', 38, 67, 'ADD', [{alumnograduacion_apellidos: ''}], 'alumnograduacion_apellidos_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 38, 68, 'ADD', [{alumnograduacion_apellidos: 'a'}], 'alumnograduacion_apellidos_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 39, 69, 'EDIT', [{alumnograduacion_apellidos: 'a.repeat(36)'}], 'alumnograduacion_apellidos_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 40, 70, 'EDIT', [{alumnograduacion_apellidos: '#alicia'}], 'alumnograduacion_apellidos_format_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 40, 71, 'EDIT', [{alumnograduacion_apellidos: 'sebas22'}], 'alumnograduacion_apellidos_format_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 41, 72, 'EDIT', [{alumnograduacion_apellidos: 'Fernández Rodríguez'}], true],
    ['alumnograduacion', 'alumnograduacion_apellidos', 42, 73, 'EDIT', [{alumnograduacion_apellidos: 'a.repeat(36)'}], 'alumnograduacion_apellidos_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 43, 74, 'SEARCH', [{alumnograduacion_apellidos: '#alicia'}], 'alumnograduacion_apellidos_format_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 43, 75, 'SEARCH', [{alumnograduacion_apellidos: 'sebas22'}], 'alumnograduacion_apellidos_format_KO'],
    ['alumnograduacion', 'alumnograduacion_apellidos', 44, 76, 'SEARCH', [{alumnograduacion_apellidos: 'Fernández Rodríguez'}], true],
    ['alumnograduacion', 'alumnograduacion_titulacion', 45, 77, 'ADD', [{alumnograduacion_titulacion: 'a'}], 'alumnograduacion_titulacion_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 45, 78, 'ADD', [{alumnograduacion_titulacion: 'aa'}], 'alumnograduacion_titulacion_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 46, 79, 'ADD', [{alumnograduacion_titulacion: 'a.repeat(5)'}], 'alumnograduacion_titulacion_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 47, 80, 'ADD', [{alumnograduacion_titulacion: 'ABC'}], 'alumnograduacion_titulacion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 47, 81, 'ADD', [{alumnograduacion_titulacion: 'ABCD'}], 'alumnograduacion_titulacion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 48, 82, 'ADD', [{alumnograduacion_titulacion: 'GREI'}], true],
    ['alumnograduacion', 'alumnograduacion_titulacion', 49, 83, 'EDIT', [{alumnograduacion_titulacion: 'a'}], 'alumnograduacion_titulacion_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 49, 84, 'EDIT', [{alumnograduacion_titulacion: 'aa'}], 'alumnograduacion_titulacion_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 50, 85, 'EDIT', [{alumnograduacion_titulacion: 'a.repeat(5)'}], 'alumnograduacion_titulacion_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 51, 86, 'EDIT', [{alumnograduacion_titulacion: 'ABC'}], 'alumnograduacion_titulacion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 51, 87, 'EDIT', [{alumnograduacion_titulacion: 'ABCD'}], 'alumnograduacion_titulacion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 52, 88, 'EDIT', [{alumnograduacion_titulacion: 'GREI'}], true],
    ['alumnograduacion', 'alumnograduacion_titulacion', 53, 89, 'SEARCH', [{alumnograduacion_titulacion: 'a.repeat(5)'}], 'alumnograduacion_titulacion_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 54, 90, 'SEARCH', [{alumnograduacion_titulacion: 'ABC'}], 'alumnograduacion_titulacion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 54, 91, 'SEARCH', [{alumnograduacion_titulacion: 'ABCD'}], 'alumnograduacion_titulacion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_titulacion', 55, 92, 'SEARCH', [{alumnograduacion_titulacion: 'GREI'}], true],
    ['alumnograduacion', 'alumnograduacion_dni', 56, 93, 'ADD', [{alumnograduacion_dni: '1234567'}], 'alumnograduacion_dni_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 56, 94, 'ADD', [{alumnograduacion_dni: '123456'}], 'alumnograduacion_dni_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 57, 95, 'ADD', [{alumnograduacion_dni: '123456789'}], 'alumnograduacion_dni_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 58, 96, 'ADD', [{alumnograduacion_dni: '1234567A'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 58, 97, 'ADD', [{alumnograduacion_dni: '12345678a'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 58, 98, 'ADD', [{alumnograduacion_dni: 'ABCDEFGHI'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 59, 99, 'ADD', [{alumnograduacion_dni: '12345678Z'}], true],
    ['alumnograduacion', 'alumnograduacion_dni', 60, 100, 'EDIT', [{alumnograduacion_dni: '1234567'}], 'alumnograduacion_dni_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 60, 101, 'EDIT', [{alumnograduacion_dni: '123456'}], 'alumnograduacion_dni_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 61, 102, 'EDIT', [{alumnograduacion_dni: '123456789'}], 'alumnograduacion_dni_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 62, 103, 'EDIT', [{alumnograduacion_dni: '1234567A'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 62, 104, 'EDIT', [{alumnograduacion_dni: '12345678a'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 62, 105, 'EDIT', [{alumnograduacion_dni: 'ABCDEFGHI'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 63, 106, 'EDIT', [{alumnograduacion_dni: '12345678Z'}], true],
    ['alumnograduacion', 'alumnograduacion_dni', 64, 107, 'SEARCH', [{alumnograduacion_dni: '123456789'}], 'alumnograduacion_dni_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 65, 108, 'SEARCH', [{alumnograduacion_dni: '12345678#'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 65, 109, 'SEARCH', [{alumnograduacion_dni: '12345678a'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 65, 110, 'SEARCH', [{alumnograduacion_dni: 'ABCDEFGHI'}], 'alumnograduacion_dni_format_KO'],
    ['alumnograduacion', 'alumnograduacion_dni', 66, 111, 'SEARCH', [{alumnograduacion_dni: '12345678Z'}], true],
    ['alumnograduacion', 'alumnograduacion_telefono', 67, 112, 'ADD', [{alumnograduacion_telefono: '12345678'}], 'alumnograduacion_telefono_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 67, 113, 'ADD', [{alumnograduacion_telefono: '1234567'}], 'alumnograduacion_telefono_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 68, 114, 'ADD', [{alumnograduacion_telefono: '1234567890'}], 'alumnograduacion_telefono_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 69, 115, 'ADD', [{alumnograduacion_telefono: '12345678A'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 69, 116, 'ADD', [{alumnograduacion_telefono: '12345#789'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 69, 117, 'ADD', [{alumnograduacion_telefono: 'ABCDEFGHI'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 70, 118, 'ADD', [{alumnograduacion_telefono: '612345678'}], true],
    ['alumnograduacion', 'alumnograduacion_telefono', 71, 119, 'EDIT', [{alumnograduacion_telefono: '12345678'}], 'alumnograduacion_telefono_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 71, 120, 'EDIT', [{alumnograduacion_telefono: '1234567'}], 'alumnograduacion_telefono_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 72, 121, 'EDIT', [{alumnograduacion_telefono: '1234567890'}], 'alumnograduacion_telefono_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 73, 122, 'EDIT', [{alumnograduacion_telefono: '12345678A'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 73, 123, 'EDIT', [{alumnograduacion_telefono: '12345#789'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 73, 124, 'EDIT', [{alumnograduacion_telefono: 'ABCDEFGHI'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 74, 125, 'EDIT', [{alumnograduacion_telefono: '612345678'}], true],
    ['alumnograduacion', 'alumnograduacion_telefono', 75, 126, 'SEARCH', [{alumnograduacion_telefono: '1234567890'}], 'alumnograduacion_telefono_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 76, 127, 'SEARCH', [{alumnograduacion_telefono: '12345678A'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 76, 128, 'SEARCH', [{alumnograduacion_telefono: '12345#789'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 76, 129, 'SEARCH', [{alumnograduacion_telefono: 'ABCDEFGHI'}], 'alumnograduacion_telefono_format_KO'],
    ['alumnograduacion', 'alumnograduacion_telefono', 77, 130, 'SEARCH', [{alumnograduacion_telefono: '612345678'}], true],
    ['alumnograduacion', 'alumnograduacion_direccion', 78, 131, 'ADD', [{alumnograduacion_direccion: ''}], 'alumnograduacion_direccion_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 79, 132, 'ADD', [{alumnograduacion_direccion: 'a'.repeat(150)}], 'alumnograduacion_direccion_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 80, 133, 'ADD', [{alumnograduacion_direccion: '#Calle Mayor, 1'}], 'alumnograduacion_direccion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 80, 134, 'ADD', [{alumnograduacion_direccion: 'Calle Mayor 1ºA'}], 'alumnograduacion_direccion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 81, 135, 'ADD', [{alumnograduacion_direccion: 'Calle Mayor'}], true],
    ['alumnograduacion', 'alumnograduacion_direccion', 82, 136, 'EDIT', [{alumnograduacion_direccion: ''}], 'alumnograduacion_direccion_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 83, 137, 'EDIT', [{alumnograduacion_direccion: 'a'.repeat(150)}], 'alumnograduacion_direccion_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 84, 138, 'EDIT', [{alumnograduacion_direccion: '#Calle Mayor, 1'}], 'alumnograduacion_direccion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 84, 139, 'EDIT', [{alumnograduacion_direccion: 'Calle Mayor 1ºA'}], 'alumnograduacion_direccion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 85, 140, 'EDIT', [{alumnograduacion_direccion: 'Calle Mayor'}], true],
    ['alumnograduacion', 'alumnograduacion_direccion', 86, 141, 'SEARCH', [{alumnograduacion_direccion: 'a'.repeat(150)}], 'alumnograduacion_direccion_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 87, 142, 'SEARCH', [{alumnograduacion_direccion: '#Calle Mayor, 1'}], 'alumnograduacion_direccion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 87, 143, 'SEARCH', [{alumnograduacion_direccion: 'Calle Mayor 1ºA'}], 'alumnograduacion_direccion_format_KO'],
    ['alumnograduacion', 'alumnograduacion_direccion', 88, 144, 'SEARCH', [{alumnograduacion_direccion: 'Calle Mayor'}], true],
    ['alumnograduacion', 'alumnograduacion_email', 89, 145, 'ADD', [{alumnograduacion_email: ''}], 'alumnograduacion_email_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 90, 146, 'ADD', [{alumnograduacion_email: 'a'.repeat(101)}], 'alumnograduacion_email_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 91, 147, 'ADD', [{alumnograduacion_email: 'a@b.c'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 91, 148, 'ADD', [{alumnograduacion_email: 'useratexample.com'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 91, 149, 'ADD', [{alumnograduacion_email: 'user@examplecom'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 91, 150, 'ADD', [{alumnograduacion_email: 'userexample.com'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 92, 151, 'ADD', [{alumnograduacion_email: 'user@example.com'}], true],
    ['alumnograduacion', 'alumnograduacion_email', 93, 152, 'EDIT', [{alumnograduacion_email: ''}], 'alumnograduacion_email_min_size_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 94, 153, 'EDIT', [{alumnograduacion_email: 'a'.repeat(101)}], 'alumnograduacion_email_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 95, 154, 'EDIT', [{alumnograduacion_email: 'a@b.c'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 95, 155, 'EDIT', [{alumnograduacion_email: 'useratexample.com'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 95, 156, 'EDIT', [{alumnograduacion_email: 'user@examplecom'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 95, 157, 'EDIT', [{alumnograduacion_email: 'userexample.com'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 96, 158, 'EDIT', [{alumnograduacion_email: 'user@example.com'}], true],
    ['alumnograduacion', 'alumnograduacion_email', 97, 159, 'SEARCH', [{alumnograduacion_email: 'a'.repeat(101)}], 'alumnograduacion_email_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 98, 160, 'SEARCH', [{alumnograduacion_email: 'a@b.c'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 98, 161, 'SEARCH', [{alumnograduacion_email: 'useratexample.com'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 98, 162, 'SEARCH', [{alumnograduacion_email: 'user@examplecom'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 98, 163, 'SEARCH', [{alumnograduacion_email: 'userexample.com'}], 'alumnograduacion_email_format_KO'],
    ['alumnograduacion', 'alumnograduacion_email', 99, 164, 'SEARCH', [{alumnograduacion_email: 'user@example.com'}], true],
    ['alumnograduacion', 'alumnograduacion_fotoacto', 114, 165, 'SEARCH', [{alumnograduacion_fotoacto: 'foto'.repeat(40)+'.jpg'}], 'alumnograduacion_fotoacto_name_max_size_KO'],
    ['alumnograduacion', 'alumnograduacion_fotoacto', 115, 166, 'SEARCH',[{alumnograduacion_fotoacto: 'fo to . j p g'}], 'alumnograduacion_fotoacto_name_format_KO'],
    ['alumnograduacion', 'alumnograduacion_fotoacto', 116, 167, 'SEARCH',[{alumnograduacion_fotoacto: 'fotografia'}], true],*/
]

let alumnograduacion_tests_files = [
    /*['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 100, 1, 'ADD', 'exists', [], 'nuevo_alumnograduacion_fotoacto_not_exists_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 101, 2, 'ADD', 'format_name_file', [{format_name_file:'foto niño.jpg'}, {type_file:'img/jpg'}, {max_size_file: 200}], 'nuevo_alumnograduacion_fotoacto_name_format_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 102, 3, 'ADD', 'type_file',[{format_name_file:'foto.png'}, {type_file:'img/png'}, {max_size_file:200}], 'nuevo_alumnograduacion_fotoacto_type_file_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 103, 4, 'ADD', 'max_size_file',[{format_name_file:'foto.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000001}], 'nuevo_alumnograduacion_fotoacto_max_size_file_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 104, 5, 'ADD', 'format_name_file', [{format_name_file:'f.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000000}], 'nuevo_alumnograduacion_fotoacto_name_min_size_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 105, 6, 'ADD', 'format_name_file', [{format_name_file:'foto'.repeat(40)+'.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000000}], 'nuevo_alumnograduacion_fotoacto_name_max_size_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 106, 7, 'ADD', 'valid', [{format_name_file:'foto.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000000}], true],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 107, 8, 'EDIT', 'exists', [], true],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 108, 9, 'EDIT', 'format_name_file', [{format_name_file:'foto niño.jpg'}, {type_file:'img/jpg'}, {max_size_file: 200}], 'nuevo_alumnograduacion_fotoacto_name_format_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 109, 10, 'EDIT', 'type_file',[{format_name_file:'foto.png'}, {type_file:'img/png'}, {max_size_file:200}], 'nuevo_alumnograduacion_fotoacto_type_file_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 110, 11, 'EDIT', 'max_size_file',[{format_name_file:'foto.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000001}], 'nuevo_alumnograduacion_fotoacto_max_size_file_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 111, 12, 'EDIT', 'format_name_file', [{format_name_file:'f.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000000}], 'nuevo_alumnograduacion_fotoacto_name_min_size_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 112, 13, 'EDIT', 'format_name_file', [{format_name_file:'foto'.repeat(21)+'.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000000}], 'nuevo_alumnograduacion_fotoacto_name_max_size_KO'],
    ['alumnograduacion', 'nuevo_alumnograduacion_fotoacto', 113, 14, 'EDIT', 'valid', [{format_name_file:'foto.jpg'}, {type_file:'img/jpg'}, {max_size_file:2000000}], true],

]


let articulo_def_tests = [
    ['articulo', 'CodigoA', 1, 'Comprobar tamaño mínimo de CodigoA', 'ADD', 'CodigoA_min_size_KO', 'El código del artículodebe tener once caracteres numéricos'],
    ['articulo', 'CodigoA', 2, 'Comprobar tamaño máximo de CodigoA', 'ADD', 'CodigoA_max_size_KO', 'El código del artículo debe tener once caracteres numéricos'],
    ['articulo', 'CodigoA', 3, 'Comprobar formato de CodigoA', 'ADD', 'CodigoA_format_KO', 'El código del artículo solo permite oncce caracteres numéricos'],
    ['articulo', 'CodigoA', 4, 'Comprobar resultado válido', 'ADD', true, ''],
    ['articulo', 'CodigoA', 5, 'Comprobar tamaño mínimo de CodigoA', 'EDIT', 'CodigoA_min_size_KO', 'El código del artículodebe tener once caracteres numéricos'],
    ['articulo', 'CodigoA', 6, 'Comprobar tamaño máximo de CodigoA', 'EDIT', 'CodigoA_max_size_KO', 'El código del artículo debe tener once caracteres numéricos'],
    ['articulo', 'CodigoA', 7, 'Comprobar formato de CodigoA', 'EDIT', 'CodigoA_format_KO', 'El código del artículo solo permite oncce caracteres numéricos'],
    ['articulo', 'CodigoA', 8, 'Comprobar resultado válido', 'EDIT', true, ''],
    ['articulo', 'CodigoA', 9, 'Comprobar tamaño máximo de CodigoA en búsqueda', 'SEARCH', 'CodigoA_max_size_KO', 'El código del artículo debe tener once caracteres numéricos'],
    ['articulo', 'CodigoA', 10, 'Comprobar formato de CodigoA en búsqueda', 'SEARCH', 'CodigoA_format_KO', 'El código del artículo debe tener solo enteros'],
    ['articulo', 'CodigoA', 11, 'Comprobar valor de búsqueda válido', 'SEARCH', true, ''],
    ['articulo', 'AutoresA', 12, 'Comprobar tamaño mínimo de AutoresA', 'ADD', 'AutoresA_min_size_KO', 'El nombre de los autores debe tener como mínimo 7 y como máximo 200 caracteres alfabéticos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'AutoresA', 13, 'Comprobar tamaño máximo de AutoresA', 'ADD', 'AutoresA_max_size_KO', 'El nombre de los autores debe tener como mínimo 7 y como máximo 200 caracteres alfabñeticos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'AutoresA', 14, 'Comprobar formato de AutoresA', 'ADD', 'AutoresA_format_KO', 'El nombre de los autores solo permite caracteres alfabéticos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'AutoresA', 15, 'Comprobar campo válido para AutoresA', 'ADD', true, ''],
    ['articulo', 'AutoresA', 16, 'Comprobar tamaño mínimo de AutoresA', 'EDIT', 'AutoresA_min_size_KO', 'El nombre de los autores debe tener como mínimo 7 y como máximo 200 caracteres alfabéticos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'AutoresA', 17, 'Comprobar tamaño máximo de AutoresA', 'EDIT', 'AutoresA_max_size_KO', 'El nombre de los autores debe tener como mínimo 7 y como máximo 200 caracteres alfabéticos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'AutoresA', 18 , 'Comprobar formato de AutoresA', 'EDIT', 'AutoresA_format_KO', 'El nombre de los autores solo puede contener caracteres alfabéticos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'AutoresA', 19, 'Comprobar campo válido de AutoresA', 'EDIT', true, ''],
    ['articulo', 'AutoresA', 20, 'Comprobar tamaño máximo de AutoresA', 'SEARCH', 'AutoresA_max_size_KO', 'El nombre de los autores no puede exceder los 200 caracteres'],
    ['articulo', 'AutoresA', 21, 'Comprobar formato de AutoresA', 'SEARCH', 'AutoresA_format_KO', 'El nombre de los autores solo permite caracteres alfabéticos incluídos ñ, acentos y espacios'],
    ['articulo', 'AutoresA', 22, 'Comprobar campo válido AutoresA', 'SEARCH', true, ''],
    ['articulo', 'TituloA', 23, 'Comprobar tamaño mínimo de TituloA', 'ADD', 'TituloA_min_size_KO', 'El título del artículo debe tener como mínimo 3 y como máximo 100 caracteres alfanuméricos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'TituloA', 24, 'Comprobar tamaño máximo de TituloA', 'ADD','TituloA_max_size_KO', 'El título del artículo debe tener vomo mínimo 3 y como máximo 100 caracteresalfanuméricos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'TituloA', 25, 'Comprobar formato de TituloA', 'ADD', 'TituloA_format_KO', 'El titulo del artículo debe estar compuesto por caracteres alfanuméricos, incluyendo ñ, acentos y espacios'],
    ['articulo', 'TituloA', 26, 'Comprobar campo válido TituloA', 'ADD', true, ''], */
]